import {
  type Asset,
  type BalanceSheetBucket,
  type MovementKind,
  type MovementSide,
  type MovementStatus,
  type Rail,
} from "@bankops/contracts";

export type MovementProfile = {
  weight: number;
  kind: MovementKind;
  side: MovementSide;
  bucket: BalanceSheetBucket;
  rail: Rail;
  assets: readonly Asset[];
  minAmountMinor: number;
  maxAmountMinor: number;
  minLatencyMs: number;
  maxLatencyMs: number;
  normalStatus: MovementStatus;
  pendingBps: number;
  failedBps: number;
  heldBps: number;
};

export const MOVEMENT_PROFILES: readonly MovementProfile[] = [
  {
    weight: 24,
    kind: "deposit_credit",
    side: "credit",
    bucket: "customer_deposits",
    rail: "ach",
    assets: ["USD"],
    minAmountMinor: 2_500_00,
    maxAmountMinor: 8_000_000_00,
    minLatencyMs: 140,
    maxLatencyMs: 1_400,
    normalStatus: "posted",
    pendingBps: 240,
    failedBps: 15,
    heldBps: 20,
  },
  {
    weight: 16,
    kind: "wire_debit",
    side: "debit",
    bucket: "settlement_cash",
    rail: "wire",
    assets: ["USD"],
    minAmountMinor: 25_000_00,
    maxAmountMinor: 22_000_000_00,
    minLatencyMs: 380,
    maxLatencyMs: 3_200,
    normalStatus: "posted",
    pendingBps: 420,
    failedBps: 35,
    heldBps: 25,
  },
  {
    weight: 5,
    kind: "deposit_credit",
    side: "credit",
    bucket: "customer_deposits",
    rail: "wire",
    assets: ["USD"],
    minAmountMinor: 50_000_00,
    maxAmountMinor: 28_000_000_00,
    minLatencyMs: 320,
    maxLatencyMs: 2_800,
    normalStatus: "posted",
    pendingBps: 240,
    failedBps: 20,
    heldBps: 20,
  },
  {
    weight: 4,
    kind: "wire_debit",
    side: "debit",
    bucket: "customer_deposits",
    rail: "wire",
    assets: ["USD"],
    minAmountMinor: 35_000_00,
    maxAmountMinor: 20_000_000_00,
    minLatencyMs: 360,
    maxLatencyMs: 3_100,
    normalStatus: "posted",
    pendingBps: 340,
    failedBps: 30,
    heldBps: 30,
  },
  {
    weight: 2,
    kind: "wire_debit",
    side: "debit",
    bucket: "rail_clearing",
    rail: "wire",
    assets: ["USD"],
    minAmountMinor: 25_000_00,
    maxAmountMinor: 18_000_000_00,
    minLatencyMs: 360,
    maxLatencyMs: 3_400,
    normalStatus: "accepted",
    pendingBps: 460,
    failedBps: 35,
    heldBps: 25,
  },
  {
    weight: 14,
    kind: "ach_debit",
    side: "debit",
    bucket: "rail_clearing",
    rail: "ach",
    assets: ["USD"],
    minAmountMinor: 900_00,
    maxAmountMinor: 2_500_000_00,
    minLatencyMs: 500,
    maxLatencyMs: 6_500,
    normalStatus: "accepted",
    pendingBps: 900,
    failedBps: 80,
    heldBps: 40,
  },
  {
    weight: 4,
    kind: "deposit_credit",
    side: "credit",
    bucket: "settlement_cash",
    rail: "ach",
    assets: ["USD"],
    minAmountMinor: 100_000_00,
    maxAmountMinor: 18_000_000_00,
    minLatencyMs: 420,
    maxLatencyMs: 5_500,
    normalStatus: "posted",
    pendingBps: 500,
    failedBps: 30,
    heldBps: 20,
  },
  {
    weight: 3,
    kind: "ach_debit",
    side: "debit",
    bucket: "settlement_cash",
    rail: "ach",
    assets: ["USD"],
    minAmountMinor: 100_000_00,
    maxAmountMinor: 16_000_000_00,
    minLatencyMs: 520,
    maxLatencyMs: 6_800,
    normalStatus: "accepted",
    pendingBps: 700,
    failedBps: 55,
    heldBps: 30,
  },
  {
    weight: 2,
    kind: "exception_hold",
    side: "debit",
    bucket: "exception_queue",
    rail: "ach",
    assets: ["USD"],
    minAmountMinor: 2_500_00,
    maxAmountMinor: 1_800_000_00,
    minLatencyMs: 600,
    maxLatencyMs: 7_500,
    normalStatus: "held",
    pendingBps: 0,
    failedBps: 0,
    heldBps: 10_000,
  },
  {
    weight: 1,
    kind: "fee_credit",
    side: "credit",
    bucket: "fee_income",
    rail: "ach",
    assets: ["USD"],
    minAmountMinor: 50_00,
    maxAmountMinor: 18_000_00,
    minLatencyMs: 140,
    maxLatencyMs: 1_600,
    normalStatus: "posted",
    pendingBps: 40,
    failedBps: 0,
    heldBps: 0,
  },
  {
    weight: 1,
    kind: "fee_credit",
    side: "credit",
    bucket: "fee_income",
    rail: "wire",
    assets: ["USD"],
    minAmountMinor: 1_000_00,
    maxAmountMinor: 75_000_00,
    minLatencyMs: 280,
    maxLatencyMs: 2_400,
    normalStatus: "posted",
    pendingBps: 30,
    failedBps: 0,
    heldBps: 0,
  },
  {
    weight: 12,
    kind: "instant_payment_credit",
    side: "credit",
    bucket: "customer_deposits",
    rail: "instant",
    assets: ["USD"],
    minAmountMinor: 250_00,
    maxAmountMinor: 750_000_00,
    minLatencyMs: 8,
    maxLatencyMs: 180,
    normalStatus: "settled",
    pendingBps: 70,
    failedBps: 20,
    heldBps: 10,
  },
  {
    weight: 3,
    kind: "ach_debit",
    side: "debit",
    bucket: "settlement_cash",
    rail: "instant",
    assets: ["USD"],
    minAmountMinor: 1_000_00,
    maxAmountMinor: 1_500_000_00,
    minLatencyMs: 10,
    maxLatencyMs: 240,
    normalStatus: "settled",
    pendingBps: 90,
    failedBps: 20,
    heldBps: 10,
  },
  {
    weight: 2,
    kind: "ach_debit",
    side: "debit",
    bucket: "rail_clearing",
    rail: "instant",
    assets: ["USD"],
    minAmountMinor: 1_000_00,
    maxAmountMinor: 1_200_000_00,
    minLatencyMs: 10,
    maxLatencyMs: 220,
    normalStatus: "settled",
    pendingBps: 110,
    failedBps: 25,
    heldBps: 10,
  },
  {
    weight: 1,
    kind: "fee_credit",
    side: "credit",
    bucket: "fee_income",
    rail: "instant",
    assets: ["USD"],
    minAmountMinor: 25_00,
    maxAmountMinor: 12_000_00,
    minLatencyMs: 8,
    maxLatencyMs: 160,
    normalStatus: "posted",
    pendingBps: 20,
    failedBps: 0,
    heldBps: 0,
  },
  {
    weight: 12,
    kind: "stablecoin_credit",
    side: "credit",
    bucket: "stablecoin_treasury",
    rail: "stablecoin",
    assets: ["USDC", "USDT", "PYUSD", "EURC"],
    minAmountMinor: 5_000_00,
    maxAmountMinor: 14_000_000_00,
    minLatencyMs: 120,
    maxLatencyMs: 1_900,
    normalStatus: "settled",
    pendingBps: 280,
    failedBps: 25,
    heldBps: 55,
  },
  {
    weight: 5,
    kind: "stablecoin_credit",
    side: "credit",
    bucket: "customer_deposits",
    rail: "stablecoin",
    assets: ["USDC", "USDT", "PYUSD", "EURC"],
    minAmountMinor: 2_500_00,
    maxAmountMinor: 9_000_000_00,
    minLatencyMs: 120,
    maxLatencyMs: 2_000,
    normalStatus: "settled",
    pendingBps: 340,
    failedBps: 25,
    heldBps: 80,
  },
  {
    weight: 10,
    kind: "stablecoin_debit",
    side: "debit",
    bucket: "stablecoin_treasury",
    rail: "stablecoin",
    assets: ["USDC", "USDT", "PYUSD", "EURC"],
    minAmountMinor: 5_000_00,
    maxAmountMinor: 12_000_000_00,
    minLatencyMs: 140,
    maxLatencyMs: 2_400,
    normalStatus: "settled",
    pendingBps: 340,
    failedBps: 35,
    heldBps: 70,
  },
  {
    weight: 4,
    kind: "stablecoin_debit",
    side: "debit",
    bucket: "customer_deposits",
    rail: "stablecoin",
    assets: ["USDC", "USDT", "PYUSD", "EURC"],
    minAmountMinor: 2_500_00,
    maxAmountMinor: 8_000_000_00,
    minLatencyMs: 140,
    maxLatencyMs: 2_500,
    normalStatus: "settled",
    pendingBps: 380,
    failedBps: 40,
    heldBps: 95,
  },
  {
    weight: 3,
    kind: "stablecoin_credit",
    side: "credit",
    bucket: "settlement_cash",
    rail: "stablecoin",
    assets: ["USDC", "USDT", "PYUSD", "EURC"],
    minAmountMinor: 25_000_00,
    maxAmountMinor: 16_000_000_00,
    minLatencyMs: 160,
    maxLatencyMs: 2_700,
    normalStatus: "settled",
    pendingBps: 330,
    failedBps: 30,
    heldBps: 80,
  },
  {
    weight: 2,
    kind: "exception_hold",
    side: "debit",
    bucket: "exception_queue",
    rail: "stablecoin",
    assets: ["USDC", "USDT", "PYUSD", "EURC"],
    minAmountMinor: 10_000_00,
    maxAmountMinor: 4_000_000_00,
    minLatencyMs: 180,
    maxLatencyMs: 3_400,
    normalStatus: "held",
    pendingBps: 0,
    failedBps: 0,
    heldBps: 10_000,
  },
  {
    weight: 2,
    kind: "stablecoin_debit",
    side: "debit",
    bucket: "rail_clearing",
    rail: "stablecoin",
    assets: ["USDC", "USDT", "PYUSD", "EURC"],
    minAmountMinor: 10_000_00,
    maxAmountMinor: 10_000_000_00,
    minLatencyMs: 150,
    maxLatencyMs: 2_800,
    normalStatus: "settled",
    pendingBps: 360,
    failedBps: 35,
    heldBps: 80,
  },
  {
    weight: 5,
    kind: "fee_credit",
    side: "credit",
    bucket: "fee_income",
    rail: "card",
    assets: ["USD"],
    minAmountMinor: 25_00,
    maxAmountMinor: 25_000_00,
    minLatencyMs: 30,
    maxLatencyMs: 420,
    normalStatus: "posted",
    pendingBps: 60,
    failedBps: 5,
    heldBps: 0,
  },
  {
    weight: 2,
    kind: "deposit_credit",
    side: "credit",
    bucket: "settlement_cash",
    rail: "card",
    assets: ["USD"],
    minAmountMinor: 5_000_00,
    maxAmountMinor: 2_000_000_00,
    minLatencyMs: 50,
    maxLatencyMs: 620,
    normalStatus: "posted",
    pendingBps: 90,
    failedBps: 10,
    heldBps: 0,
  },
  {
    weight: 1,
    kind: "exception_hold",
    side: "debit",
    bucket: "exception_queue",
    rail: "card",
    assets: ["USD"],
    minAmountMinor: 500_00,
    maxAmountMinor: 300_000_00,
    minLatencyMs: 60,
    maxLatencyMs: 760,
    normalStatus: "held",
    pendingBps: 0,
    failedBps: 0,
    heldBps: 10_000,
  },
  {
    weight: 2,
    kind: "reversal_credit",
    side: "credit",
    bucket: "customer_deposits",
    rail: "internal_ledger",
    assets: ["USD"],
    minAmountMinor: 500_00,
    maxAmountMinor: 600_000_00,
    minLatencyMs: 8,
    maxLatencyMs: 80,
    normalStatus: "posted",
    pendingBps: 20,
    failedBps: 0,
    heldBps: 0,
  },
  {
    weight: 3,
    kind: "reserve_transfer",
    side: "credit",
    bucket: "settlement_cash",
    rail: "internal_ledger",
    assets: ["USD"],
    minAmountMinor: 50_000_00,
    maxAmountMinor: 16_000_000_00,
    minLatencyMs: 4,
    maxLatencyMs: 45,
    normalStatus: "posted",
    pendingBps: 15,
    failedBps: 0,
    heldBps: 0,
  },
  {
    weight: 3,
    kind: "reserve_transfer",
    side: "debit",
    bucket: "settlement_cash",
    rail: "internal_ledger",
    assets: ["USD"],
    minAmountMinor: 50_000_00,
    maxAmountMinor: 16_000_000_00,
    minLatencyMs: 4,
    maxLatencyMs: 45,
    normalStatus: "posted",
    pendingBps: 15,
    failedBps: 0,
    heldBps: 0,
  },
  {
    weight: 3,
    kind: "reserve_transfer",
    side: "credit",
    bucket: "reserve_cash",
    rail: "internal_ledger",
    assets: ["USD"],
    minAmountMinor: 100_000_00,
    maxAmountMinor: 18_000_000_00,
    minLatencyMs: 4,
    maxLatencyMs: 40,
    normalStatus: "posted",
    pendingBps: 15,
    failedBps: 0,
    heldBps: 0,
  },
  {
    weight: 3,
    kind: "reserve_transfer",
    side: "debit",
    bucket: "reserve_cash",
    rail: "internal_ledger",
    assets: ["USD"],
    minAmountMinor: 100_000_00,
    maxAmountMinor: 18_000_000_00,
    minLatencyMs: 4,
    maxLatencyMs: 40,
    normalStatus: "posted",
    pendingBps: 15,
    failedBps: 0,
    heldBps: 0,
  },
  {
    weight: 2,
    kind: "reserve_transfer",
    side: "credit",
    bucket: "stablecoin_treasury",
    rail: "internal_ledger",
    assets: ["USDC", "USDT", "PYUSD", "EURC"],
    minAmountMinor: 20_000_00,
    maxAmountMinor: 12_000_000_00,
    minLatencyMs: 4,
    maxLatencyMs: 45,
    normalStatus: "posted",
    pendingBps: 20,
    failedBps: 0,
    heldBps: 0,
  },
  {
    weight: 2,
    kind: "reserve_transfer",
    side: "debit",
    bucket: "stablecoin_treasury",
    rail: "internal_ledger",
    assets: ["USDC", "USDT", "PYUSD", "EURC"],
    minAmountMinor: 20_000_00,
    maxAmountMinor: 12_000_000_00,
    minLatencyMs: 4,
    maxLatencyMs: 45,
    normalStatus: "posted",
    pendingBps: 20,
    failedBps: 0,
    heldBps: 0,
  },
  {
    weight: 1,
    kind: "exception_hold",
    side: "debit",
    bucket: "exception_queue",
    rail: "instant",
    assets: ["USD"],
    minAmountMinor: 10_000_00,
    maxAmountMinor: 900_000_00,
    minLatencyMs: 30,
    maxLatencyMs: 650,
    normalStatus: "held",
    pendingBps: 0,
    failedBps: 0,
    heldBps: 10_000,
  },
];

export const TOTAL_PROFILE_WEIGHT = MOVEMENT_PROFILES.reduce(
  (total, profile) => total + profile.weight,
  0,
);
